config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
              path: 'users', 
              path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  devise_for :club_users, 
              path: 'club_users',
              path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'login', to: 'pages#login'
  get 'sign_up', to: 'pages#sign_up'

  resources :clubs, except: [:show] do 
  	member do 
  		get :toggle_active_status
  	end
  end
  get '/:id', to: 'clubs#show', as: 'club_show'

  root to:'pages#home'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/club.rb
class Club < ApplicationRecord
  include PlaceholderConcern
  
  has_many :teams
  accepts_nested_attributes_for :teams, 
                                reject_if: lambda { |attrs| attrs['name'].blank? }
  
  has_many :campaigns
  accepts_nested_attributes_for :campaigns,
                                reject_if: lambda { |attrs| 
                                                      attrs['recruit_type'].blank? || 
                                                      attrs['ideal_start_date'].blank? ||
                                                      attrs['job_description'].blank? ||
                                                      attrs['compensation'].blank? ||
                                                      attrs['passport_requirements'].blank? }

  has_many :people
  accepts_nested_attributes_for :people,
                                reject_if: lambda { |attrs| 
                                                      attrs['first_name'].blank? || 
                                                      attrs['last_name'].blank? ||
                                                      attrs['email'].blank? }

  validates_presence_of :club_name, :sport, :address, :main_image, :sport_icon, :active_status
	enum active_status: { inactive: 0, active: 1}
	
  extend FriendlyId
  	friendly_id :club_name, use: :slugged

  after_initialize :set_defaults

  	# Setting a default value of the main_image.
	def set_defaults
		self.main_image ||= PlaceholderConcern.image_generator(height: '200', width: '300')
    self.sport_icon ||= PlaceholderConcern.image_generator(height: '40', width: '40')
	end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
	before_action :set_club, only: [:show, :edit, :update, :destroy, :toggle_active_status]
	access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

	def edit
	end

	def update
		respond_to do |format|
			if @club.update(club_params)
				format.html { redirect_to clubs_path, notice: 'Your record sucessfully updated.'}
			else 
				format.html { render :edit}
			end
		end
	end

	def toggle_active_status
		if @club.inactive?
			@club.active!
		elsif @club.active?
			@club.inactive!
		end
		redirect_to club_show_path, notice: 'Club status was updated.'
	end

	def destroy
		@club.destroy
	    respond_to do |format|
	      format.html { redirect_to root_path, notice: 'Record was removed.' }
	    end
	end

	def index
		@clubs = Club.all
		@page_title = "Sports clubs"
	end

	def new
		@club = Club.new
		1.times { @club.teams.build }
		1.times { @club.campaigns.build }
		1.times { @club.people.build }
		@page_title = "New sports clubs"
	end

	def create
		@club = Club.new(club_params)

		respond_to do |format|
			if @club.save
				format.html { redirect_to clubs_path, notice: 'Your club is now live.' }
			else 
				format.html { render :new }
		end
	end

	def show
		@page_title = @club.club_name
		@seo_keywords = @club.sport
	end

end

private
	def club_params
    	params.require(:club).permit(
			:club_name, 
			:sport, 
			:club_role, 
			:main_image, 
			:address, 
			:active_status, 
			:sport_icon, 
			teams_attributes: [:name], 
			people_attributes: [:first_name, :last_name, :position, :email], 
			campaigns_attributes: [:recruit_type, :player_type, :ideal_start_date, :job_description, :compensation, :passport_requirements ]
    	)
	end

	def set_club
		@club = Club.friendly.find(params[:id])
	end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_club.html.erb
<p><%= club.club_name %></p>
<p><%= club.address %></p>
<p>
	<%= club.sport %>
	<%= image_tag club.sport_icon unless club.sport_icon.nil? %>		
</p>
<%= image_tag club.main_image unless club.main_image.nil? %>
<p><%= link_to "More info", club_show_path(club) %></p>
<br>

app/views/clubs/_form.html.erb
<h3>General info</h3>
<%= form_for(club) do |f| %>
	<div class="field">
		<%= f.label :club_name %>
		<%= f.text_field :club_name %>
	</div>

	<div class="field">
		<%= f.label :sport %>
		<%= f.text_field :sport %>
	</div>

	<div class="field">
		<%= f.label :club_role %>
		<%= f.text_field :club_role %>
	</div>

	<div class="field">
		<%= f.label :address %>
		<%= f.text_field :address %>
	</div>
	
	<h3>Teams</h3>
	 <ul>
	 	<%= f.fields_for :teams do |team_form| %>
	 		<li>
	 			<%= team_form.label :name %>
	 			<%= team_form.text_field :name %>
	 		</li>
	 		<hr>
	 	<% end %>
	 </ul>
	
	<h3>People</h3>
	 <ul>
	 	<%= f.fields_for :people do |person_form| %>
	 		<li>
	 			<%= person_form.label :first_name %>
	 			<%= person_form.text_field :first_name %>
	 		</li>
	 		<li>
	 			<%= person_form.label :last_name %>
	 			<%= person_form.text_field :last_name %>
	 		</li>
	 		<li>
	 			<%= person_form.label :position %>
	 			<%= person_form.text_field :position %>
	 		</li>
	 		<li>
	 			<%= person_form.label :email %>
	 			<%= person_form.text_field :email %>
	 		</li>
	 		<hr>
	 	<% end %>
	 </ul>
	
	<h3>Campaigns</h3>
	 <ul>
	 	<%= f.fields_for :campaigns do |campaign_form| %>
	 		<li>
	 			<%= campaign_form.label :recruit_type %>
	 			<%= campaign_form.text_field :recruit_type %>
	 		</li>
	 		<li>
	 			<%= campaign_form.label :player_type %>
	 			<%= campaign_form.text_field :player_type %>
	 		</li>
	 		<li>
	 			<%= campaign_form.label :ideal_start_date %>
	 			<%= campaign_form.text_field :ideal_start_date %>
	 		</li>
	 		<li>
	 			<%= campaign_form.label :job_description %>
	 			<%= campaign_form.text_field :job_description %>
	 		</li>
	 		<li>
	 			<%= campaign_form.label :compensation %>
	 			<%= campaign_form.text_field :compensation %>
	 		</li>
	 		<li>
	 			<%= campaign_form.label :passport_requirements %>
	 			<%= campaign_form.text_field :passport_requirements %>
	 		</li>
	 		<hr>
	 	<% end %>
	 </ul>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/clubs/edit.html.erb
<h1>Change your info.</h1>

<%= render 'form', club: @club %>

app/views/clubs/index.html.erb
<h1>Clubs</h1>

<!-- rendering a collection via partials -->
<%= render @clubs %>

app/views/clubs/new.html.erb
<div class="form">
	<h1>Getting started.</h1>

	<!-- 'club' is a local variable that is passed into the form that takes the form of the @club instance variable -->
	<%= render 'form', club: @club %>
</div>

app/views/clubs/show.html.erb
<h1><%= @club.club_name %></h1>

<% if logged_in?(:site_admin) %>
	<h4><%= link_to @club.active_status, toggle_active_status_club_path(@club) %></h4>
<% else %>
	<h4><%= @club.active_status %></h4>
<% end %>

<%= image_tag @club.main_image unless @club.main_image.nil? %>
<p><%= @club.address %></p>
<p><%= @club.sport %></p>
<p><%= link_to "Change details", edit_club_path if logged_in?(:site_admin) %></p>
<p><%= link_to "Back", clubs_path %></p>
<p><%= link_to "Delete", club_path, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %></p>

<hr>
<h3>Teams</h3>
<% @club.teams.each do |team| %>
	<li><%= team.name %></li>
<% end %>

<hr>
<h3>People</h3>
<% @club.people.each do |person| %>
	<li><%= person.first_name %></li>
	<li><%= person.last_name %></li>
	<li><%= person.position %></li>
	<li><%= person.email %></li>
	<br>
<% end %>

<hr>
<h3>Recruitment campaigns</h3>
<% @club.campaigns.each do |campaign| %>
	<li>Created <%= distance_of_time_in_words(campaign.created_at, Time.now) %> days ago</li>
	<li><%= campaign.recruit_type %></li>
	<li><%= campaign.ideal_start_date %></li>
	<li><%= campaign.job_description %></li>
	<li><%= campaign.passport_requirements %></li>
	<br>
<% end %>