config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
              path: 'users', 
              path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  devise_for :club_users, 
              path: 'club_users',
              path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'login', to: 'pages#login'
  get 'sign_up', to: 'pages#sign_up'

  resources :clubs, except: [:show] do 
  	member do 
  		get :toggle_active_status
  	end
  end
  get '/:id', to: 'clubs#show', as: 'club_show'

  root to:'pages#home'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/about.html.erb
<h1>About us page</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Contact us</h1>
<p><%= number_to_phone "07817727747" %></p>

app/views/pages/home.html.erb
<% if current_user.is_a?(User) %>
	<h1>Hi, <%= current_user.initials %></h1>
<% end %>

<p>Find me in app/views/pages/home.html.erb</p>

<h2 class="heading">Sporty people</h2>
<%= @pros.inspect %>

<h2>Clubs</h2>
<%= @clubs.inspect %>

app/views/pages/login.html.erb
<h2>Club login</h2>
<%= link_to "Login", club_user_session_path %>


<h2>Sporty person login</h2>
<%= link_to "Login", user_session_path %>

app/views/pages/sign_up.html.erb
<h2>Club sign up</h2>
<%= link_to "Sign up", new_club_user_registration_path %>


<h2>Sporty person sign up</h2>
<%= link_to "Sign up", new_user_registration_path %>